language: python
dist: trusty
sudo: required
cache:
  pip: true
  directories:
    - bin/sources/

python:
- 2.7

install:
 - bash ./install.sh

script:
 - wxtoimg -h
 - sox --version
 - lame --version
 - wxtoimg -V
 - wxmap -V
 - bin/dump1090-stream-parser.py --help
 - convert -help
 - ./genpasstable.py
